### PR TITLE
keywords changes meta

### PR DESCRIPTION
**Pull request by Sanket403**
keywords changes meta

### CODE REVIEW

**Review by zemse — APPROVED** [review]
Looks ok.

**Comment by kavimrvavi** [comment]
ok

**Review by Ashish0235 — APPROVED** [review]
Looking all Good.

**Review by Ashish0235 — APPROVED** [review]
Changes approved.

**Review by kavimrvavi — APPROVED** [review]

**Review by vikashkmpards — APPROVED** [review]

**Review by chiragbajaj2010 — APPROVED** [review]

**Pull request merged**
